apiVersion: v1
kind: Pod
metadata:
  name: tf-gpu
spec:
  containers:
    - name: tf
      image: tensorflow/tensorflow:latest-gpu
      command: ["sleep", "inf"]
      #resources:
      #  limits:
      #    nvidia.com/gpu: 1
      env:
        - name: PATH
          value: "/bin:/usr/bin:/usr/local/bin:/opt/nvidia-driver/bin"
        - name: LD_LIBRARY_PATH
          value: "/opt/nvidia-driver/lib64"
      securityContext:
        privileged: true
        seLinuxOptions:
          type: spc_t
      volumeMounts:
        - name: nvidia-driver
          mountPath: /opt/nvidia-driver
  nodeSelector:
    gpu: nvidia
  volumes:
  - name: nvidia-driver
    hostPath:
      path: /opt/nvidia-driver
      type: DirectoryOrCreate
